### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by gbalabasquer**
@MrChico same for this repo. Note that `ds-auth` has be upgraded to 7d9c6c8 in order to maintain compatibility with e.g. `ds-token`. At some point `ds-auth` should be bumped everywhere.

### CODE REVIEW

**Comment by MrChico** [comment]
hmm, we did just upgrade `ds-auth` everywhere to `bd00871dff1f9e6aea76b8c56a7bc28ab9c602b4`, including ds-token https://github.com/dapphub/ds-token/tree/master/lib, and we should use the same commit here

**Comment by gbalabasquer** [comment]
Yeah not sure what I was looking for. Just reverted the last commit.

**Comment by gbalabasquer** [comment]
Maybe it is easier you push directly the 3 upgrades to `master`.

**Comment by MrChico** [comment]
squashed and merged

**Pull request merged**
